services:
  mysql:
    image: mysql:8.0
    container_name: apbd_mysql
    restart: always
    command:
    - --slow_query_log=ON
    - --slow_query_log_file=/var/lib/mysql/slow.log
    - --long_query_time=0.5
    - --log_queries_not_using_indexes=ON
    - --min_examined_row_limit=100
    - --performance_schema=ON
    - --log_output=FILE,TABLE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos
      MYSQL_USER: apbd_user
      MYSQL_PASSWORD: apbd_pass
    ports:
      - "3308:3306"  # Externally accessible for debugging
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/logs:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # rl_agent:
  #   build: ../agent
  #   container_name: rl_agent
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   working_dir: /app
  #   volumes:
  #     - ./rl_agent:/app
  #     - ./data/models:/app/models
    # environment:
    #   MYSQL_HOST: mysql  # Changed from localhost to mysql
    #   MYSQL_PORT: 3306
    #   MYSQL_USER: apbd_user
    #   MYSQL_PASSWORD: apbd_pass
    #   MYSQL_DATABASE: pos
    # command: python agent_api.py  # Start API server
    # ports:
    #   - "8000:8000"  # API port

  # interface:
  #   build: ./interface
  #   container_name: interface
  #   depends_on:
  #     - rl_agent
  #   working_dir: /app
  #   volumes:
  #     - ./interface:/app
  #   environment:
  #     AGENT_API_URL: http://rl_agent:8000
  #   ports:
  #     - "8501:8501"  # Streamlit interface
  #   command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

volumes:
  mysql_data:
  grafana_data: